/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReaderRouteImport } from './routes/reader'
import { Route as ApiPublicImageRouteImport } from './routes/api/public/image'
import { Route as ApiPublicProviderSelftestRouteImport } from './routes/api/public/provider-selftest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderRoute = ReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImageRoute = ApiPublicImageRouteImport.update({
  id: '/api/public/image',
  path: '/api/public/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProviderSelftestRoute =
  ApiPublicProviderSelftestRouteImport.update({
    id: '/api/public/provider-selftest',
    path: '/api/public/provider-selftest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reader': typeof ReaderRoute
  '/api/public/image': typeof ApiPublicImageRoute
  '/api/public/provider-selftest': typeof ApiPublicProviderSelftestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reader': typeof ReaderRoute
  '/api/public/image': typeof ApiPublicImageRoute
  '/api/public/provider-selftest': typeof ApiPublicProviderSelftestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reader': typeof ReaderRoute
  '/api/public/image': typeof ApiPublicImageRoute
  '/api/public/provider-selftest': typeof ApiPublicProviderSelftestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/reader' | '/api/public/image' | '/api/public/provider-selftest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reader' | '/api/public/image' | '/api/public/provider-selftest'
  id:
    | '__root__'
    | '/'
    | '/reader'
    | '/api/public/image'
    | '/api/public/provider-selftest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReaderRoute: typeof ReaderRoute
  ApiPublicImageRoute: typeof ApiPublicImageRoute
  ApiPublicProviderSelftestRoute: typeof ApiPublicProviderSelftestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/image': {
      id: '/api/public/image'
      path: '/api/public/image'
      fullPath: '/api/public/image'
      preLoaderRoute: typeof ApiPublicImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/provider-selftest': {
      id: '/api/public/provider-selftest'
      path: '/api/public/provider-selftest'
      fullPath: '/api/public/provider-selftest'
      preLoaderRoute: typeof ApiPublicProviderSelftestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReaderRoute: ReaderRoute,
  ApiPublicImageRoute: ApiPublicImageRoute,
  ApiPublicProviderSelftestRoute: ApiPublicProviderSelftestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
